### ISSUE TITLE
Hang when indexing projects with untidy `go.mod`

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/scip-go#53]
Seems to reproduce reliably, at least when tried with a 16-core machine on Linux.

Configuration:
- scip-go: a2e8de5276360fb1be4834aaf563daeef909cb15
- Sourcegraph monorepo: (`monitoring/` subdir)
  - 888069af56bc1ee4477f8c4f117feda86a283394 (on `main`)
  - 248c1e2e3106865051b8a45866d729353d49b87e (this ref needs to be fetched separately)

Go version 1.20.8 (based on asdf configuration at that commit)

Originally reported in [Slack](https://sourcegraph.slack.com/archives/C04MYFW01NV/p1695932723790039). [Failed job](https://github.com/sourcegraph/sourcegraph/actions/runs/6340027995/job/17220527561?pr=57148)

<img width="787" alt="image" src="https://github.com/sourcegraph/scip-go/assets/93103176/b62118d9-adb4-4849-a10d-59bbef629bf1">

A goroutine seems to be stuck on

```
runtime.selectgo(0xc0001fd930, 0xc0001fd908, 0xc0001fd9c0?, 0x0, 0xc00030a000?, 0x1)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/select.go:327 +0x7be fp=0xc0001fd8c8 sp=0xc0001fd788 pc=0x44c2de
github.com/sourcegraph/scip-go/internal/output.WithProgressParallel.func2(0xcbe600?)
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/internal/output/output.go:79 +0xc5 fp=0xc0001fd960 sp=0xc0001fd8c8 pc=0xa46fe5
```

See full results below:

<details>

```
scip-go
Resolving module name
  Go standard library version:  go1.19
  Resolved module name       :  github.com/sourcegraph/sourcegraph/monitoring

Configuration:
  Skip Implementations: false
  Skip Test           : false
Loading Packages
SIGABRT: abort
PC=0x4709a1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/sys_linux_amd64.s:554 +0x21 fp=0x7ffeb25e7b78 sp=0x7ffeb25e7b70 pc=0x4709a1
runtime.futexsleep(0x10000000000?, 0x0?, 0x3?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/os_linux.go:69 +0x36 fp=0x7ffeb25e7bc8 sp=0x7ffeb25e7b78 pc=0x4351b6
runtime.notesleep(0x1149548)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/lock_futex.go:160 +0x87 fp=0x7ffeb25e7c00 sp=0x7ffeb25e7bc8 pc=0x40e3a7
runtime.mPark(...)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:1531
runtime.stopm()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:2335 +0x8c fp=0x7ffeb25e7c30 sp=0x7ffeb25e7c00 pc=0x43fb0c
runtime.findRunnable()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:3025 +0xabc fp=0x7ffeb25e7d38 sp=0x7ffeb25e7c30 pc=0x4413bc
runtime.schedule()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:3378 +0xb1 fp=0x7ffeb25e7d70 sp=0x7ffeb25e7d38 pc=0x4421f1
runtime.park_m(0xc000102b60?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:3529 +0x12d fp=0x7ffeb25e7da0 sp=0x7ffeb25e7d70 pc=0x44270d
runtime.mcall()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/asm_amd64.s:452 +0x43 fp=0x7ffeb25e7db0 sp=0x7ffeb25e7da0 pc=0x46c843

goroutine 1 [select]:
runtime.gopark(0xc0001fd930?, 0x2?, 0xa8?, 0x9f?, 0xc0001fd90c?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001fd788 sp=0xc0001fd768 pc=0x43bc36
runtime.selectgo(0xc0001fd930, 0xc0001fd908, 0xc0001fd9c0?, 0x0, 0xc00030a000?, 0x1)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/select.go:327 +0x7be fp=0xc0001fd8c8 sp=0xc0001fd788 pc=0x44c2de
github.com/sourcegraph/scip-go/internal/output.WithProgressParallel.func2(0xcbe600?)
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/internal/output/output.go:79 +0xc5 fp=0xc0001fd960 sp=0xc0001fd8c8 pc=0xa46fe5
github.com/sourcegraph/scip-go/internal/output.withTitleStatic({0xbcdd56, 0x10}, 0x1, 0xc0001fda30)
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/internal/output/output.go:105 +0xb7 fp=0xc0001fd9e0 sp=0xc0001fd960 pc=0xa471d7
github.com/sourcegraph/scip-go/internal/output.withTitle({0xbcdd56?, 0x0?}, 0xc0001fda60?)
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/internal/output/output.go:95 +0x4d fp=0xc0001fda10 sp=0xc0001fd9e0 pc=0xa470cd
github.com/sourcegraph/scip-go/internal/output.WithProgressParallel(0xc000312110, {0xbcdd56, 0x10}, 0xc000312108, 0x1)
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/internal/output/output.go:77 +0xfb fp=0xc0001fda70 sp=0xc0001fda10 pc=0xa46ebb
github.com/sourcegraph/scip-go/internal/output.WithProgress({0xbcdd56, 0x10}, 0xc000304ae0)
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/internal/output/output.go:56 +0x77 fp=0xc0001fdac8 sp=0xc0001fda70 pc=0xa46d57
github.com/sourcegraph/scip-go/internal/loader.LoadPackages({{0xc000134240, 0x22}, {0xc0001340c0, 0xc}, {0xc000306000, 0x2d}, {0xc000128584, 0x6}, 0x0, 0x0, ...}, ...)
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/internal/loader/loader.go:78 +0x2b9 fp=0xc0001fdb18 sp=0xc0001fdac8 pc=0xa54319
github.com/sourcegraph/scip-go/internal/index.Index(0xc000318000, {{0xc000134240, 0x22}, {0xc0001340c0, 0xc}, {0xc000306000, 0x2d}, {0xc000128584, 0x6}, 0x0, ...})
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/internal/index/scip.go:100 +0x172 fp=0xc0001fdbf0 sp=0xc0001fdb18 pc=0xa5f2d2
main.mainErr()
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/cmd/scip-go/main.go:210 +0x9f3 fp=0xc0001fdf28 sp=0xc0001fdbf0 pc=0xa7d2d3
main.main()
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/cmd/scip-go/main.go:92 +0x1d fp=0xc0001fdf80 sp=0xc0001fdf28 pc=0xa7c83d
runtime.main()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:250 +0x207 fp=0xc0001fdfe0 sp=0xc0001fdf80 pc=0x43b807
runtime.goexit()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001fdfe8 sp=0xc0001fdfe0 pc=0x46ea81

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:381 +0xd6 fp=0xc000078fb0 sp=0xc000078f90 pc=0x43bc36
runtime.goparkunlock(...)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:387
runtime.forcegchelper()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:305 +0xb0 fp=0xc000078fe0 sp=0xc000078fb0 pc=0x43ba70
runtime.goexit()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000078fe8 sp=0xc000078fe0 pc=0x46ea81
created by runtime.init.6
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:381 +0xd6 fp=0xc000079780 sp=0xc000079760 pc=0x43bc36
runtime.goparkunlock(...)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000797c8 sp=0xc000079780 pc=0x4262ce
runtime.gcenable.func1()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000797e0 sp=0xc0000797c8 pc=0x41b586
runtime.goexit()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000797e8 sp=0xc0000797e0 pc=0x46ea81
created by runtime.gcenable
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc0000a0000?, 0xcb85f0?, 0x1?, 0x0?, 0x0?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:381 +0xd6 fp=0xc000079f70 sp=0xc000079f50 pc=0x43bc36
runtime.goparkunlock(...)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x11488a0)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000079fa0 sp=0xc000079f70 pc=0x4241f3
runtime.bgscavenge(0x0?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc000079fc8 sp=0xc000079fa0 pc=0x4247c5
runtime.gcenable.func2()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/mgc.go:179 +0x26 fp=0xc000079fe0 sp=0xc000079fc8 pc=0x41b526
runtime.goexit()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000079fe8 sp=0xc000079fe0 pc=0x46ea81
created by runtime.gcenable
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1a0?, 0x10f8c20?, 0xa0?, 0x61?, 0xc000078770?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:381 +0xd6 fp=0xc000078628 sp=0xc000078608 pc=0x43bc36
runtime.runfinq()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000787e0 sp=0xc000078628 pc=0x41a5c7
runtime.goexit()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000787e8 sp=0xc0000787e0 pc=0x46ea81
created by runtime.createfing
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/mfinal.go:163 +0x45

goroutine 70 [chan send]:
runtime.gopark(0x1?, 0x1?, 0x90?, 0x40?, 0x22?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001f9eb8 sp=0xc0001f9e98 pc=0x43bc36
runtime.chansend(0xc000376000, 0xc0001f9fa8, 0x1, 0x0?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/chan.go:259 +0x42e fp=0xc0001f9f40 sp=0xc0001f9eb8 pc=0x4082ae
runtime.chansend1(0x0?, 0x0?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/chan.go:145 +0x1d fp=0xc0001f9f70 sp=0xc0001f9f40 pc=0x407e5d
github.com/sourcegraph/scip-go/internal/parallel.Run.func1()
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/internal/parallel/parallel.go:27 +0xcc fp=0xc0001f9fe0 sp=0xc0001f9f70 pc=0xa46b0c
runtime.goexit()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001f9fe8 sp=0xc0001f9fe0 pc=0x46ea81
created by github.com/sourcegraph/scip-go/internal/parallel.Run
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/internal/parallel/parallel.go:21 +0x5b

goroutine 82 [semacquire]:
runtime.gopark(0x0?, 0x0?, 0xe0?, 0xe4?, 0x0?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:381 +0xd6 fp=0xc0003876f8 sp=0xc0003876d8 pc=0x43bc36
runtime.goparkunlock(...)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/proc.go:387
runtime.semacquire1(0xc000312118, 0x0?, 0x1, 0x0, 0x0?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/sema.go:160 +0x20f fp=0xc000387760 sp=0xc0003876f8 pc=0x44d3cf
sync.runtime_Semacquire(0x0?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/sema.go:62 +0x27 fp=0xc000387798 sp=0xc000387760 pc=0x46a767
sync.(*WaitGroup).Wait(0x0?)
        /home/varun/.asdf/installs/golang/1.20.8/go/src/sync/waitgroup.go:116 +0x4b fp=0xc0003877c0 sp=0xc000387798 pc=0x475f4b
github.com/sourcegraph/scip-go/internal/output.WithProgressParallel.func1()
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/internal/output/output.go:73 +0x26 fp=0xc0003877e0 sp=0xc0003877c0 pc=0xa47046
runtime.goexit()
        /home/varun/.asdf/installs/golang/1.20.8/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0003877e8 sp=0xc0003877e0 pc=0x46ea81
created by github.com/sourcegraph/scip-go/internal/output.WithProgressParallel
        /home/varun/.asdf/installs/golang/1.20.8/packages/pkg/mod/github.com/sourcegraph/scip-go@v0.1.6/internal/output/output.go:72 +0x9e
```

</details>

**Comment by varungandhi-src** [comment]
The hang is because of an untidy repo, as the last command that is run is:

```
2023/09/29 20:32:44 87.323014ms for GOROOT=/home/varun/.asdf/installs/golang/1.20.8/go GOPATH=/home/varun/.asdf/installs/golang/1.20.8/packages GO111MODULE= GOPROXY= PWD=/home/varun/sourcegraph/monitoring go list -e -json=Name,ImportPath,Error,Dir,GoFiles,IgnoredGoFiles,IgnoredOtherFiles,CFiles,CgoFiles,CXXFiles,MFiles,HFiles,FFiles,SFiles,SwigFiles,SwigCXXFiles,SysoFiles,TestGoFiles,XTestGoFiles,CompiledGoFiles,DepOnly,Imports,ImportMap,TestImports,XTestImports,Module -compiled=true -test=true -export=false -deps=true -find=false -- ./...
```

However, if you run that separately, you get:

```
go: updates to go.mod needed; to update it:
        go mod tidy
```

If I run `go mod tidy`, then indexing finishes quickly.
