### ISSUE TITLE
Do not generate blank index on panic

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/scip-go#59]
This can be confusing as someone may still try to use it without paying attention to the error/panic.

**Comment by varungandhi-src** [comment]
We saw a panic earlier with https://github.com/simoncwaterer/example1code/commit/d0e28142e7feb3331ac6da8bf1cb0ca5dcd80669

```
Loading Packages
panic: Should not be possible to have nil module for userland package: git.taservs.net/ljohnston/example2/ex git.taservs.net/ljohnston/example2/ex

goroutine 20 [running]:
github.com/sourcegraph/scip-go/internal/loader.normalizePackage(0x140002ce550, 0x140004ec480)
        /Users/varun/Code/scip-go/internal/loader/loader.go:147 +0x6b4
github.com/sourcegraph/scip-go/internal/loader.addImportsToPkgs(0x10544b940?, 0x1400025fd10?, 0x140004ec480)
        /Users/varun/Code/scip-go/internal/loader/loader.go:48 +0x58
github.com/sourcegraph/scip-go/internal/loader.addImportsToPkgs(0x14000149f28?, 0x1400032a2b0?, 0x140004ec600)
        /Users/varun/Code/scip-go/internal/loader/loader.go:52 +0xf4
github.com/sourcegraph/scip-go/internal/loader.LoadPackages.func1()
        /Users/varun/Code/scip-go/internal/loader/loader.go:85 +0x168
github.com/sourcegraph/scip-go/internal/parallel.Run.func1()
        /Users/varun/Code/scip-go/internal/parallel/parallel.go:26 +0x88
created by github.com/sourcegraph/scip-go/internal/parallel.Run
        /Users/varun/Code/scip-go/internal/parallel/parallel.go:22 +0x68
```
